### ISSUE TITLE
SimpleTouch constructor: compilation error 

### ISSUE THREAD

**Issue by IamDN** [tillnagel/simpletouch#3]
win 7/ Processing 3.21

throw error when compiling costructor  SimpleTouch 
 (any of SimpleTouch example code)

java.lang.NoSuchMethodError:processing.core.PApllet.registerDispose(Ljava/lang/Object;)V

same error with Processing 3.12, 3.02 and win 10 (TOIO library instaled)

java.lang.RuntimeException: java.lang.NoSuchMethodError: processing.core.PApplet.registerDispose(Ljava/lang/Object;)V
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:461)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: processing.core.PApplet.registerDispose(Ljava/lang/Object;)V
	at de.fhpotsdam.simpletouch.SimpleTouch.<init>(Unknown Source)
	at de.fhpotsdam.simpletouch.SimpleTouch.<init>(Unknown Source)
	at ImageTouch.setup(ImageTouch.java:30)
	at processing.core.PApplet.handleDraw(PApplet.java:2378)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:871)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by tillnagel** [comment]
Fixed with new release 0.2.2

Download it at http://tillnagel.com/simpletouch/
